server:
  port: 8080

#Eureka配置
eureka:
  client:
    register-with-eureka: false # 该module是消费服务的，所以不用向Eureka server 注册自己 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

