server:
  port: 3344

#spring
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crystal0579/springcloud-config.git #这里用得是https， 而不是git的 SSH,也就是公共文件的仓库